[platformio]
default_envs = north
src_dir = .

[env]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600
build_flags =
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1

[env:north]
build_flags =
  ${env.build_flags}
  -DNODE_ID=\"North\"
  -DNODE_LABEL=\"north\"
upload_port = /dev/ttyACM0
monitor_port = /dev/ttyACM0

[env:south]
build_flags =
  ${env.build_flags}
  -DNODE_ID=\"South\"
  -DNODE_LABEL=\"south\"
upload_port = /dev/ttyACM1
monitor_port = /dev/ttyACM1

[env:east]
build_flags =
  ${env.build_flags}
  -DNODE_ID=\"East\"
  -DNODE_LABEL=\"east\"
upload_port = /dev/ttyACM2
monitor_port = /dev/ttyACM2

[env:west]
build_flags =
  ${env.build_flags}
  -DNODE_ID=\"West\"
  -DNODE_LABEL=\"west\"
upload_port = /dev/ttyACM3
monitor_port = /dev/ttyACM3
